[package]
name = "rorbcat"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
itm = { path = "../../crates/itm" }
collector = { path = "../../crates/collector" }
