[package]
name = "rorbcat"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
cobs = { path = "../../crates/cobs" }
oflow = { path = "../../crates/oflow" }
itm = { path = "../../crates/itm" }
